#Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# antibody
source <(antibody init)
antibody bundle < "$HOME"/.zsh_plugins

# include zsh config
for file in "$HOME"/.zsh/**/*.zsh
do
  source "$file"
done

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f "$HOME"/.p10k.zsh ]] || source "$HOME"/.p10k.zsh

# asdf
[[ ! -f "$HOME"/.asdf/asdf.sh ]] || source "$HOME"/.asdf/asdf.sh

# asdf functions completions
FPATH=$ASDF_DIR/completions:$FPATH

# brew functions completions
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && source /usr/local/etc/profile.d/autojump.sh

# init functions completions from FPATH
autoload -Uz compinit
compinit

# User configuration
# Always work in a tmux session if tmux is installed
# https://github.com/chrishunt/dot-files/blob/master/.zshrc
if which tmux > /dev/null 2>&1;  then
  if [ "$TERM" != "screen-256color" ] && [  "$TERM" != "screen" ]; then
    tmux attach -t workspace || tmux new -s workspace; exit
  fi
fi
